# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadingScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deleted_accs(object):
    def setupUi(self, deleted_accs):
        deleted_accs.setObjectName("deleted_accs")
        deleted_accs.resize(631, 326)
        self.dropShadowFrame = QtWidgets.QFrame(deleted_accs)
        self.dropShadowFrame.setGeometry(QtCore.QRect(0, 0, 631, 326))
        self.dropShadowFrame.setStyleSheet("QFrame#dropShadowFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 85, 127, 255), stop:1 rgba(85, 170, 255, 255));\n"
"border-radius:15px;\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label = QtWidgets.QLabel(self.dropShadowFrame)
        self.label.setGeometry(QtCore.QRect(220, 20, 191, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("MJDB_ICON.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(10, 230, 611, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"background-color: rgb(170, 170, 255);\n"
"border-radius: 10px;\n"
"border-style:none;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.472, x2:1, y2:0.494, stop:0 rgba(0, 170, 127, 255), stop:1 rgba(0, 227, 166, 255));\n"
"border-radius:10px;\n"
"}\n"
"")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_2.setGeometry(QtCore.QRect(260, 270, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(67, 67, 67);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_3.setGeometry(QtCore.QRect(420, 300, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(112, 112, 112);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_4.setGeometry(QtCore.QRect(0, 180, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(67, 67, 67);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_5.setGeometry(QtCore.QRect(10, 300, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(67, 67, 67);")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(deleted_accs)
        QtCore.QMetaObject.connectSlotsByName(deleted_accs)

    def retranslateUi(self, deleted_accs):
        _translate = QtCore.QCoreApplication.translate
        deleted_accs.setWindowTitle(_translate("deleted_accs", "deleted_accs"))
        self.label_2.setText(_translate("deleted_accs", "CHARGEMENT..."))
        self.label_3.setText(_translate("deleted_accs", "<strong>Devolopé par</strong> MJDB S.A.R.L"))
        self.label_4.setText(_translate("deleted_accs", "Bienvenue sur MJDB"))
        self.label_5.setText(_translate("deleted_accs", "v1.4"))
