# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 223)
        MainWindow.setMinimumSize(QtCore.QSize(480, 223))
        MainWindow.setMaximumSize(QtCore.QSize(480, 223))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-1, -1, 481, 231))
        self.frame_2.setStyleSheet("QFrame#frame_2{;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(137, 137, 204, 255), stop:1 rgba(90, 90, 249, 255));\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.line_edit_pass = QtWidgets.QLineEdit(self.frame_2)
        self.line_edit_pass.setGeometry(QtCore.QRect(139, 131, 201, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_pass.sizePolicy().hasHeightForWidth())
        self.line_edit_pass.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        self.line_edit_pass.setFont(font)
        self.line_edit_pass.setAutoFillBackground(False)
        self.line_edit_pass.setStyleSheet("background:transparent;\n"
"border:none;\n"
"border-bottom:1px solid #9f9f9f;")
        self.line_edit_pass.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.line_edit_pass.setInputMask("")
        self.line_edit_pass.setText("")
        self.line_edit_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_pass.setObjectName("line_edit_pass")
        self.b_login = QtWidgets.QPushButton(self.frame_2)
        self.b_login.setGeometry(QtCore.QRect(9, 181, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        self.b_login.setFont(font)
        self.b_login.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.475, y1:0, x2:0.534, y2:1, stop:0 rgba(206, 206, 206, 255), stop:1 rgba(156, 156, 156, 255));\n"
"}\n"
"QPushButton:hover {background-color: rgb(0, 223, 164);\n"
" }")
        self.b_login.setObjectName("b_login")
        self.label_login = QtWidgets.QLabel(self.frame_2)
        self.label_login.setGeometry(QtCore.QRect(10, 90, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_login.sizePolicy().hasHeightForWidth())
        self.label_login.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_login.setObjectName("label_login")
        self.label_pass = QtWidgets.QLabel(self.frame_2)
        self.label_pass.setGeometry(QtCore.QRect(9, 131, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_pass.setFont(font)
        self.label_pass.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_pass.setObjectName("label_pass")
        self.list_colabs = QtWidgets.QComboBox(self.frame_2)
        self.list_colabs.setGeometry(QtCore.QRect(139, 91, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        self.list_colabs.setFont(font)
        self.list_colabs.setStyleSheet("QComboBox{\n"
"    border-radius:5px;\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.483, y1:0, x2:0.513, y2:0.989, stop:0 rgba(197, 197, 197, 255), stop:1 rgba(120, 120, 120, 255));\n"
"    selection-color:white;\n"
"}\n"
"QComboBox:hover {\n"
"    \n"
"    background-color: qlineargradient(spread:reflect, x1:0.457, y1:0.5, x2:0.436, y2:1, stop:0 rgba(0, 230, 169, 255), stop:1 rgba(0, 200, 147, 255));\n"
" }\n"
"")
        self.list_colabs.setEditable(False)
        self.list_colabs.setIconSize(QtCore.QSize(16, 16))
        self.list_colabs.setObjectName("list_colabs")
        self.wrong_pass = QtWidgets.QLabel(self.frame_2)
        self.wrong_pass.setGeometry(QtCore.QRect(139, 181, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        self.wrong_pass.setFont(font)
        self.wrong_pass.setStyleSheet("color: rgb(255, 0, 0);\n"
"border-radius:20px;")
        self.wrong_pass.setText("")
        self.wrong_pass.setObjectName("wrong_pass")
        self.sign_in = QtWidgets.QPushButton(self.frame_2)
        self.sign_in.setGeometry(QtCore.QRect(359, 181, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        self.sign_in.setFont(font)
        self.sign_in.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.475, y1:0, x2:0.534, y2:1, stop:0 rgba(206, 206, 206, 255), stop:1 rgba(156, 156, 156, 255));\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 170, 255);\n"
" }")
        self.sign_in.setObjectName("sign_in")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(0, 0, 481, 81))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.l_mjdb = QtWidgets.QLabel(self.frame)
        self.l_mjdb.setGeometry(QtCore.QRect(10, 4, 101, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_mjdb.sizePolicy().hasHeightForWidth())
        self.l_mjdb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.l_mjdb.setFont(font)
        self.l_mjdb.setText("")
        self.l_mjdb.setPixmap(QtGui.QPixmap("MJDB_ICON.ico"))
        self.l_mjdb.setScaledContents(True)
        self.l_mjdb.setObjectName("l_mjdb")
        self.l_date = QtWidgets.QLabel(self.frame)
        self.l_date.setGeometry(QtCore.QRect(270, 40, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        self.l_date.setFont(font)
        self.l_date.setObjectName("l_date")
        self.l_timer = QtWidgets.QLabel(self.frame)
        self.l_timer.setGeometry(QtCore.QRect(390, 40, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        self.l_timer.setFont(font)
        self.l_timer.setObjectName("l_timer")
        self.title_bar = QtWidgets.QFrame(self.frame)
        self.title_bar.setGeometry(QtCore.QRect(-1, 0, 481, 31))
        self.title_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.mini = QtWidgets.QPushButton(self.title_bar)
        self.mini.setGeometry(QtCore.QRect(420, 10, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.mini.setFont(font)
        self.mini.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(206, 137, 0);\n"
"}")
        self.mini.setText("")
        self.mini.setObjectName("mini")
        self.close_btn = QtWidgets.QPushButton(self.title_bar)
        self.close_btn.setGeometry(QtCore.QRect(450, 10, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.close_btn.setFont(font)
        self.close_btn.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(211, 0, 0);\n"
"}")
        self.close_btn.setText("")
        self.close_btn.setObjectName("close_btn")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(-3, 69, 491, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MJDB"))
        self.line_edit_pass.setPlaceholderText(_translate("MainWindow", "Password"))
        self.b_login.setText(_translate("MainWindow", "Login"))
        self.b_login.setShortcut(_translate("MainWindow", "Return"))
        self.label_login.setText(_translate("MainWindow", "LOGIN"))
        self.label_pass.setText(_translate("MainWindow", "PASSWORD"))
        self.sign_in.setText(_translate("MainWindow", "S\'inscrire"))
        self.sign_in.setShortcut(_translate("MainWindow", "Return"))
        self.l_date.setText(_translate("MainWindow", "00/00/00"))
        self.l_timer.setText(_translate("MainWindow", "00:00:00"))
