# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Date.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_efed(object):
    def setupUi(self, efed):
        efed.setObjectName("efed")
        efed.setWindowModality(QtCore.Qt.ApplicationModal)
        efed.resize(451, 181)
        self.frame = QtWidgets.QFrame(efed)
        self.frame.setGeometry(QtCore.QRect(0, 0, 451, 181))
        self.frame.setStyleSheet("QFrame#frame{\n"
"    border-radius:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.116919 rgba(0, 115, 173, 255), stop:0.944118 rgba(0, 0, 0, 255));\n"
"    \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.title_bar = QtWidgets.QFrame(self.frame)
        self.title_bar.setGeometry(QtCore.QRect(-1, -1, 461, 41))
        self.title_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.mini = QtWidgets.QPushButton(self.title_bar)
        self.mini.setGeometry(QtCore.QRect(420, 10, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.mini.setFont(font)
        self.mini.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(206, 137, 0);\n"
"}")
        self.mini.setText("")
        self.mini.setObjectName("mini")
        self.label = QtWidgets.QLabel(self.title_bar)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 40, 451, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.dateEdit = QtWidgets.QDateEdit(self.frame)
        self.dateEdit.setGeometry(QtCore.QRect(200, 80, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("QDateEdit{\n"
"    border-radius:5px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.483, y1:0, x2:0.513, y2:0.989, stop:0 rgba(197, 197, 197, 255), stop:1 rgba(120, 120, 120, 255));\n"
"}\n"
"QDateEdit:hover {\n"
"    \n"
"    background-color: rgb(85, 170, 255);\n"
" }")
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 6, 6), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.new_op = QtWidgets.QPushButton(self.frame)
        self.new_op.setGeometry(QtCore.QRect(330, 140, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.new_op.setFont(font)
        self.new_op.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.475, y1:0, x2:0.534, y2:1, stop:0 rgba(206, 206, 206, 255), stop:1 rgba(156, 156, 156, 255));\n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    \n"
"    background-color: rgb(0, 223, 164);\n"
" }")
        self.new_op.setObjectName("new_op")

        self.retranslateUi(efed)
        QtCore.QMetaObject.connectSlotsByName(efed)

    def retranslateUi(self, efed):
        _translate = QtCore.QCoreApplication.translate
        efed.setWindowTitle(_translate("efed", "efed"))
        self.label.setText(_translate("efed", "Date"))
        self.label_2.setText(_translate("efed", "Choisir une date:"))
        self.dateEdit.setDisplayFormat(_translate("efed", "dd/MM/yyyy"))
        self.new_op.setText(_translate("efed", "Confirmer"))
