# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Inscription.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_colab(object):
    def setupUi(self, edit_colab):
        edit_colab.setObjectName("edit_colab")
        edit_colab.setWindowModality(QtCore.Qt.ApplicationModal)
        edit_colab.resize(523, 378)
        edit_colab.setMinimumSize(QtCore.QSize(523, 378))
        edit_colab.setMaximumSize(QtCore.QSize(523, 378))
        self.frame = QtWidgets.QFrame(edit_colab)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 531, 381))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(-10, 0, 541, 401))
        self.frame_3.setMinimumSize(QtCore.QSize(541, 401))
        self.frame_3.setMaximumSize(QtCore.QSize(541, 401))
        self.frame_3.setStyleSheet("QFrame#frame_3{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 85, 127, 255), stop:1 rgba(0, 170, 127, 255));\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 110, 281, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(40)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.prenom = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        self.prenom.setFont(font)
        self.prenom.setStyleSheet("background:transparent;\n"
"border:none;\n"
"border-bottom:1px solid #9f9f9f;\n"
"color: rgb(255, 255, 255);")
        self.prenom.setInputMask("")
        self.prenom.setText("")
        self.prenom.setObjectName("prenom")
        self.horizontalLayout.addWidget(self.prenom)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(60)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.nom = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        self.nom.setFont(font)
        self.nom.setStyleSheet("background:transparent;\n"
"border:none;\n"
"border-bottom:1px solid #9f9f9f;\n"
"color: rgb(255, 255, 255);")
        self.nom.setObjectName("nom")
        self.horizontalLayout_3.addWidget(self.nom)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(30)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.password = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        self.password.setFont(font)
        self.password.setStyleSheet("background:transparent;\n"
"border:none;\n"
"border-bottom:1px solid #9f9f9f;\n"
"color: rgb(255, 255, 255);")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.horizontalLayout_4.addWidget(self.password)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.sign = QtWidgets.QPushButton(self.frame_3)
        self.sign.setGeometry(QtCore.QRect(410, 340, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        self.sign.setFont(font)
        self.sign.setObjectName("sign")
        self.wrong = QtWidgets.QLabel(self.frame_3)
        self.wrong.setGeometry(QtCore.QRect(30, 330, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        self.wrong.setFont(font)
        self.wrong.setStyleSheet("color: rgb(255, 0, 0);")
        self.wrong.setText("")
        self.wrong.setObjectName("wrong")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(10, 0, 531, 91))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(30)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("MJDB_ICON.ico"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(170, 50, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.title_bar = QtWidgets.QFrame(self.frame_2)
        self.title_bar.setGeometry(QtCore.QRect(-1, 0, 531, 31))
        self.title_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.mini = QtWidgets.QPushButton(self.title_bar)
        self.mini.setGeometry(QtCore.QRect(470, 10, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.mini.setFont(font)
        self.mini.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(206, 137, 0);\n"
"}")
        self.mini.setText("")
        self.mini.setObjectName("mini")
        self.close_btn = QtWidgets.QPushButton(self.title_bar)
        self.close_btn.setGeometry(QtCore.QRect(500, 10, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.close_btn.setFont(font)
        self.close_btn.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(211, 0, 0);\n"
"}")
        self.close_btn.setText("")
        self.close_btn.setObjectName("close_btn")
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setGeometry(QtCore.QRect(7, 79, 531, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(edit_colab)
        QtCore.QMetaObject.connectSlotsByName(edit_colab)

    def retranslateUi(self, edit_colab):
        _translate = QtCore.QCoreApplication.translate
        edit_colab.setWindowTitle(_translate("edit_colab", "edit_colab"))
        self.label.setText(_translate("edit_colab", "Prénom"))
        self.prenom.setPlaceholderText(_translate("edit_colab", "Prénom"))
        self.label_2.setText(_translate("edit_colab", "Nom"))
        self.nom.setPlaceholderText(_translate("edit_colab", "Nom"))
        self.label_3.setText(_translate("edit_colab", "Password"))
        self.password.setPlaceholderText(_translate("edit_colab", "Password"))
        self.sign.setText(_translate("edit_colab", "S\'inscrire"))
        self.label_6.setText(_translate("edit_colab", "Inscription"))
